name: Deploy to EC2 (test branch)

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 server
        env:
          HOST: ${{ secrets.EC2_HOST }}
          KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@$HOST << 'EOF'
            cd /home/ec2-user/portfolio-inner-page
            git pull origin test
            sudo docker stop portfolio-app-prod || true
            sudo docker rm portfolio-app-prod || true

            docker build -t portfolio-app .
            
            sudo docker run -d -p 3000:3000 --name portfolio-app-prod portfolio-app

          EOF
